name: pyfhd
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - astropy
  - configargparse
  - matplotlib
  - numba
  - numpy
  - pytest
  - pytest-cov
  - scipy
  - setuptools
  - sphinx
  - colorama
  - importlib_resources
  - h5py
  - pre-commit
  - pip
  - pip:
    - sphinx-rtd-theme
    - sphinx-argparse
    - myst-parser
    - healpy
    